function out1 = nonlinear_dynamics_observer(in1,in2,F)
%NONLINEAR_DYNAMICS_OBSERVER
%    OUT1 = NONLINEAR_DYNAMICS_OBSERVER(IN1,IN2,F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    23-Sep-2020 21:36:45

x_hat_1 = in2(1,:);
x_hat_2 = in2(2,:);
x_hat_3 = in2(3,:);
x_hat_4 = in2(4,:);
y1 = in1(1,:);
y2 = in1(2,:);
t2 = cos(x_hat_2);
t3 = sin(x_hat_2);
t4 = x_hat_4.^2;
t5 = t2.^2;
t6 = t5.*(3.0./2.0e+1);
t7 = t6-1.1e+1./2.0e+1;
t8 = 1.0./t7;
out1 = [x_hat_1.*-1.31e+2+x_hat_3+y1.*1.31e+2;x_hat_2.*(-1.270000000000172e+2)+x_hat_4+y2.*1.270000000000172e+2;x_hat_1.*-4.29e+3+x_hat_2.*3.6787+y1.*4.29e+3-y2.*3.6787-t8.*(F-t2.*t3.*1.4715+t3.*t4.*(3.0./1.0e+2));x_hat_2.*(-4.099443800001114e+3)+y2.*4.099443800001114e+3+t8.*(t3.*(-5.3955)+F.*t2+t2.*t3.*t4.*(3.0./1.0e+2)).*5.0];
